// Package preflight_kit_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package preflight_kit_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ExperimentExecutionAOCreatedVia.
const (
	ExperimentExecutionAOCreatedViaAPI      ExperimentExecutionAOCreatedVia = "API"
	ExperimentExecutionAOCreatedViaCLI      ExperimentExecutionAOCreatedVia = "CLI"
	ExperimentExecutionAOCreatedViaSCHEDULE ExperimentExecutionAOCreatedVia = "SCHEDULE"
	ExperimentExecutionAOCreatedViaUI       ExperimentExecutionAOCreatedVia = "UI"
)

// Defines values for ExperimentExecutionStepActionAOActionKind.
const (
	ATTACK   ExperimentExecutionStepActionAOActionKind = "ATTACK"
	BASIC    ExperimentExecutionStepActionAOActionKind = "BASIC"
	CHECK    ExperimentExecutionStepActionAOActionKind = "CHECK"
	LOADTEST ExperimentExecutionStepActionAOActionKind = "LOAD_TEST"
	OTHER    ExperimentExecutionStepActionAOActionKind = "OTHER"
)

// Defines values for ExperimentExecutionStepActionAOStepType.
const (
	ACTION ExperimentExecutionStepActionAOStepType = "ACTION"
)

// Defines values for ExperimentExecutionStepWaitAOStepType.
const (
	WAIT ExperimentExecutionStepWaitAOStepType = "WAIT"
)

// Defines values for ExperimentExecutionVariableAOOrigin.
const (
	ExperimentExecutionVariableAOOriginENVIRONMENT ExperimentExecutionVariableAOOrigin = "ENVIRONMENT"
	ExperimentExecutionVariableAOOriginEXECUTION   ExperimentExecutionVariableAOOrigin = "EXECUTION"
	ExperimentExecutionVariableAOOriginEXPERIMENT  ExperimentExecutionVariableAOOrigin = "EXPERIMENT"
	ExperimentExecutionVariableAOOriginSCHEDULE    ExperimentExecutionVariableAOOrigin = "SCHEDULE"
)

// Defines values for MutatingHttpMethod.
const (
	DELETE MutatingHttpMethod = "DELETE"
	POST   MutatingHttpMethod = "POST"
	PUT    MutatingHttpMethod = "PUT"
)

// Defines values for PreflightKitErrorStatus.
const (
	Errored PreflightKitErrorStatus = "errored"
	Failed  PreflightKitErrorStatus = "failed"
)

// Defines values for ReadHttpMethod.
const (
	GET ReadHttpMethod = "GET"
)

// AbstractExperimentExecutionStepAO A step that is executed as part of an experiment.
type AbstractExperimentExecutionStepAO struct {
	// CustomLabel Custom label assigned during experiment design to express the intention of this step
	CustomLabel *string `json:"customLabel,omitempty"`

	// Ended Timestamp when this experiment step ended
	Ended *time.Time `json:"ended,omitempty"`

	// Id Unique identifier of this step execution
	Id *openapi_types.UUID `json:"id,omitempty"`

	// IgnoreFailure Whether the experiment should fail/error immediately in case this step fails/errors.
	IgnoreFailure *bool `json:"ignoreFailure,omitempty"`

	// Parameters Step-specific parameters of the experiment step configuration
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// PredecessorId Unique identifier of the step execution that precedes this step, null if it is the first step of a lane
	PredecessorId *openapi_types.UUID `json:"predecessorId,omitempty"`

	// Reason Reason in case this experiment step execution failed or errored
	Reason *string `json:"reason,omitempty"`

	// Started Timestamp when this experiment step was started
	Started *time.Time `json:"started,omitempty"`

	// State Current state of this step in the experiment (e.g. RUNNING, FAILED, ERRORED, COMPLETED)
	State *string `json:"state,omitempty"`

	// StepType Type of this step execution (e.g. ACTION, WAIT)
	StepType string `json:"stepType"`
	union    json.RawMessage
}

// AttributeAO An attributes (key-value-pair) that is associated to a target
type AttributeAO struct {
	// Key The key of the attribute, may be associated multiple times to the same target
	Key string `json:"key"`

	// Value The value of the attribute
	Value string `json:"value"`
}

// BlastRadiusAO Blast radius that is applied to define the set of targets as well as an optional random subset
type BlastRadiusAO struct {
	// Maximum In case a fixed number of as subset of specified targets should be effected
	Maximum *int32 `json:"maximum,omitempty"`

	// Percentage In case a percentage subset of the specified targets should be effected
	Percentage *int32 `json:"percentage,omitempty"`

	// Predicate Query defining the overall superset of targets being effected
	Predicate *TargetPredicate `json:"predicate,omitempty"`

	// TargetType Target type that is effected by that action
	TargetType *string `json:"targetType,omitempty"`
}

// CancelResult defines model for CancelResult.
type CancelResult struct {
	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *PreflightKitError `json:"error,omitempty"`
}

// DescribingEndpointReference HTTP endpoint which the Steadybit platform/agent could communicate with.
type DescribingEndpointReference struct {
	Method ReadHttpMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// ExperimentExecutionAO A single experiment execution that was triggered from a single experiment.
type ExperimentExecutionAO struct {
	// CanceledBy The user that connected the hub
	CanceledBy *UserSummaryAO `json:"canceledBy,omitempty"`

	// Created Timestamp when the experiment was created
	Created *time.Time `json:"created,omitempty"`

	// CreatedBy The user that connected the hub
	CreatedBy *UserSummaryAO `json:"createdBy,omitempty"`

	// CreatedVia The creation trigger that caused this experiment execution to be started
	CreatedVia *ExperimentExecutionAOCreatedVia `json:"createdVia,omitempty"`

	// Ended Timestamp when the experiment ended
	Ended *time.Time `json:"ended,omitempty"`

	// ExecutionProperties The properties of the experiment execution
	ExecutionProperties *map[string]interface{} `json:"executionProperties,omitempty"`

	// ExperimentProperties The properties of the experiment at the time when the execution was created
	ExperimentProperties *map[string]interface{} `json:"experimentProperties,omitempty"`

	// ExperimentVersion Experiment design version which can be used to identify changes between experiment runs
	ExperimentVersion *int32 `json:"experimentVersion,omitempty"`

	// Hypothesis The hypothesis that is validated by the experiment
	Hypothesis *string `json:"hypothesis,omitempty"`

	// Id Unique experiment execution id that identifies this specific experiment execution
	Id *int32 `json:"id,omitempty"`

	// Key Unique experiment key that identifies the experiment. Combination of `team key` and increasing number
	Key *string `json:"key,omitempty"`

	// Name Name of the experiment to easily identify the experiment
	Name *string `json:"name,omitempty"`

	// Reason Reason in case the experiment execution failed or errored
	Reason *string `json:"reason,omitempty"`

	// Requested Timestamp when the experiment was requested
	Requested *time.Time `json:"requested,omitempty"`

	// Started Timestamp when the experiment was started
	Started *time.Time `json:"started,omitempty"`

	// State Current state of the experiment (e.g. CREATED, RUNNING, FAILED, ERRORED, COMPLETED)
	State *string `json:"state,omitempty"`

	// Steps The steps that are executed in parallel or sequence in the experiment.
	Steps *[]AbstractExperimentExecutionStepAO `json:"steps,omitempty"`

	// Variables Variables and their origins that have been used for this execution
	Variables *map[string]ExperimentExecutionVariableAO `json:"variables,omitempty"`
}

// ExperimentExecutionAOCreatedVia The creation trigger that caused this experiment execution to be started
type ExperimentExecutionAOCreatedVia string

// ExperimentExecutionStepActionAO An action-step that is executed as part of an experiment.
type ExperimentExecutionStepActionAO struct {
	// ActionId Unique identifier of the action that is executed in this step
	ActionId *string `json:"actionId,omitempty"`

	// ActionKind Kind of the action (e.g. attack, check, loadtest)
	ActionKind *ExperimentExecutionStepActionAOActionKind `json:"actionKind,omitempty"`

	// CustomLabel Custom label assigned during experiment design to express the intention of this step
	CustomLabel *string `json:"customLabel,omitempty"`

	// Ended Timestamp when this experiment step ended
	Ended *time.Time `json:"ended,omitempty"`

	// Id Unique identifier of this step execution
	Id *openapi_types.UUID `json:"id,omitempty"`

	// IgnoreFailure Whether the experiment should fail/error immediately in case this step fails/errors.
	IgnoreFailure *bool `json:"ignoreFailure,omitempty"`

	// Parameters Step-specific parameters of the experiment step configuration
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// PredecessorId Unique identifier of the step execution that precedes this step, null if it is the first step of a lane
	PredecessorId *openapi_types.UUID `json:"predecessorId,omitempty"`

	// Radius Blast radius that is applied to define the set of targets as well as an optional random subset
	Radius *BlastRadiusAO `json:"radius,omitempty"`

	// Reason Reason in case this experiment step execution failed or errored
	Reason *string `json:"reason,omitempty"`

	// Started Timestamp when this experiment step was started
	Started *time.Time `json:"started,omitempty"`

	// State Current state of this step in the experiment (e.g. RUNNING, FAILED, ERRORED, COMPLETED)
	State *string `json:"state,omitempty"`

	// StepType Type of this step execution (e.g. ACTION, WAIT)
	StepType ExperimentExecutionStepActionAOStepType `json:"stepType"`

	// TargetExecutions List of targets that are expected to be effected by this action. This list may change in case targets aren't available at the specific time of execution
	TargetExecutions *[]TargetAO `json:"targetExecutions,omitempty"`

	// TotalTargetCount Amount of targets that are effect int total
	TotalTargetCount *int64 `json:"totalTargetCount,omitempty"`
}

// ExperimentExecutionStepActionAOActionKind Kind of the action (e.g. attack, check, loadtest)
type ExperimentExecutionStepActionAOActionKind string

// ExperimentExecutionStepActionAOStepType Type of this step execution (e.g. ACTION, WAIT)
type ExperimentExecutionStepActionAOStepType string

// ExperimentExecutionStepWaitAO A wait step that is executed as part of an experiment.
type ExperimentExecutionStepWaitAO struct {
	// CustomLabel Custom label assigned during experiment design to express the intention of this step
	CustomLabel *string `json:"customLabel,omitempty"`

	// Ended Timestamp when this experiment step ended
	Ended *time.Time `json:"ended,omitempty"`

	// Id Unique identifier of this step execution
	Id *openapi_types.UUID `json:"id,omitempty"`

	// IgnoreFailure Whether the experiment should fail/error immediately in case this step fails/errors.
	IgnoreFailure *bool `json:"ignoreFailure,omitempty"`

	// Parameters Step-specific parameters of the experiment step configuration
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// PredecessorId Unique identifier of the step execution that precedes this step, null if it is the first step of a lane
	PredecessorId *openapi_types.UUID `json:"predecessorId,omitempty"`

	// Reason Reason in case this experiment step execution failed or errored
	Reason *string `json:"reason,omitempty"`

	// Started Timestamp when this experiment step was started
	Started *time.Time `json:"started,omitempty"`

	// State Current state of this step in the experiment (e.g. RUNNING, FAILED, ERRORED, COMPLETED)
	State *string `json:"state,omitempty"`

	// StepType Type of this step execution (e.g. ACTION, WAIT)
	StepType ExperimentExecutionStepWaitAOStepType `json:"stepType"`
}

// ExperimentExecutionStepWaitAOStepType Type of this step execution (e.g. ACTION, WAIT)
type ExperimentExecutionStepWaitAOStepType string

// ExperimentExecutionVariableAO Variables and their origins that have been used for this execution
type ExperimentExecutionVariableAO struct {
	Origin *ExperimentExecutionVariableAOOrigin `json:"origin,omitempty"`
	Value  *string                              `json:"value,omitempty"`
}

// ExperimentExecutionVariableAOOrigin defines model for ExperimentExecutionVariableAO.Origin.
type ExperimentExecutionVariableAOOrigin string

// MutatingEndpointReference HTTP endpoint which the Steadybit platform/agent could communicate with.
type MutatingEndpointReference struct {
	Method MutatingHttpMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// MutatingEndpointReferenceWithCallInterval defines model for MutatingEndpointReferenceWithCallInterval.
type MutatingEndpointReferenceWithCallInterval struct {
	// CallInterval At what frequency should the state endpoint be called? Takes durations in the format of `100ms` or `10s`.
	CallInterval *string            `json:"callInterval,omitempty"`
	Method       MutatingHttpMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// MutatingHttpMethod defines model for MutatingHttpMethod.
type MutatingHttpMethod string

// PreflightDescription Provides details about a possible preflight, e.g., what configuration options it has, how to present it to end-users and how to trigger the preflight.
type PreflightDescription struct {
	// Cancel HTTP endpoint which the Steadybit platform/agent could communicate with.
	Cancel *MutatingEndpointReference `json:"cancel,omitempty"`

	// Description Description for end-users to help them understand what the preflight is doing.
	Description string `json:"description"`

	// Icon An icon that is used to identify your preflight in the ui. Needs to be a data-uri containing an image.
	Icon *string `json:"icon,omitempty"`

	// Id A technical ID that is used to uniquely identify this type of preflight. You will typically want to use something like `org.example.my-fancy-preflight`.
	Id string `json:"id"`

	// Label A human-readable label for the preflight.
	Label string `json:"label"`

	// Start HTTP endpoint which the Steadybit platform/agent could communicate with.
	Start MutatingEndpointReference `json:"start"`

	// Status HTTP endpoint which the Steadybit platform/agent could communicate with.
	Status MutatingEndpointReferenceWithCallInterval `json:"status"`

	// TargetAttributeIncludes A list of attributes of targets that are populated to the preflight in the experiment execution. If the list is empty, no attributes are populated.
	TargetAttributeIncludes []string `json:"targetAttributeIncludes"`

	// Version The version of the preflight. Remember to increase the value everytime you update the definitions. The platform will ignore any definition changes with the same preflight version. We do recommend usage of semver strings.
	Version string `json:"version"`
}

// PreflightKitError An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
type PreflightKitError struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status * failed - The preflight has detected some failures, for example a failing test which has been implemented by the preflight. The preflight will be canceled, if this status is returned by the status endpoint. * errored - There was a technical error while executing the preflight. Will be marked as red in the platform. The preflight will be canceled, if this status is returned by the status endpoint.
	Status *PreflightKitErrorStatus `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// PreflightKitErrorStatus * failed - The preflight has detected some failures, for example a failing test which has been implemented by the preflight. The preflight will be canceled, if this status is returned by the status endpoint. * errored - There was a technical error while executing the preflight. Will be marked as red in the platform. The preflight will be canceled, if this status is returned by the status endpoint.
type PreflightKitErrorStatus string

// PreflightList Lists all preflights that the platform/agent could execute.
type PreflightList struct {
	Preflights []DescribingEndpointReference `json:"preflights"`
}

// ReadHttpMethod defines model for ReadHttpMethod.
type ReadHttpMethod string

// StartResult defines model for StartResult.
type StartResult struct {
	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *PreflightKitError `json:"error,omitempty"`
}

// StatusResult defines model for StatusResult.
type StatusResult struct {
	// Completed the agent will continue to poll the status endpoint as long as completed is false and no error is set
	Completed bool `json:"completed"`

	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *PreflightKitError `json:"error,omitempty"`
}

// TargetAO A target that is expected to be effected by this action.
type TargetAO struct {
	// AgentHostname The agent that processed this target-action command and forwarded it to the proper extension instance.
	AgentHostname *string `json:"agentHostname,omitempty"`

	// Attributes A set of attributes that have been discovered for this target. A key may be associated multiple time to a single target.
	Attributes *[]AttributeAO `json:"attributes,omitempty"`

	// Name Identifier of the target that is expected to be effected
	Name *string `json:"name,omitempty"`

	// Reason Reason on a per target-level why the experiment failed or errored. If this step didn't failed or errored (`state != 'FAILED' and state != 'ERRORED') the reason is `null`.
	Reason *string `json:"reason,omitempty"`

	// ReasonDetails Optional additional reason details on a per target-level why the the experiment failed or errored.
	ReasonDetails *string `json:"reasonDetails,omitempty"`

	// Source The source (i.e. call to the extension) that caused the step to error or fail.
	Source *string `json:"source,omitempty"`

	// State State of this specific step on a per target-level.
	State *string `json:"state,omitempty"`

	// Type Type of the target that is expected to be effected
	Type *string `json:"type,omitempty"`
}

// TargetPredicate Query defining the overall superset of targets being effected
type TargetPredicate = map[string]interface{}

// UserSummaryAO The user that connected the hub
type UserSummaryAO struct {
	Email *string `json:"email,omitempty"`

	// Name Name of the user
	Name       *string `json:"name,omitempty"`
	PictureUrl *string `json:"pictureUrl,omitempty"`

	// Username Username of the user, internal identifier of Steadybit
	Username string `json:"username"`
}

// CancelPreflightResponse defines model for CancelPreflightResponse.
type CancelPreflightResponse struct {
	union json.RawMessage
}

// DescribePreflightResponse defines model for DescribePreflightResponse.
type DescribePreflightResponse struct {
	union json.RawMessage
}

// PreflightListResponse defines model for PreflightListResponse.
type PreflightListResponse struct {
	union json.RawMessage
}

// PreflightStatusResponse defines model for PreflightStatusResponse.
type PreflightStatusResponse struct {
	union json.RawMessage
}

// StartPreflightResponse defines model for StartPreflightResponse.
type StartPreflightResponse struct {
	union json.RawMessage
}

// CancelPreflightRequestBody defines model for CancelPreflightRequestBody.
type CancelPreflightRequestBody struct {
	PreflightActionExecutionId uuid.UUID `json:"preflightActionExecutionId"`
}

// StartPreflightRequestBody defines model for StartPreflightRequestBody.
type StartPreflightRequestBody struct {
	// ExperimentExecution A single experiment execution that was triggered from a single experiment.
	ExperimentExecution        ExperimentExecutionAO `json:"experimentExecution"`
	PreflightActionExecutionId uuid.UUID             `json:"preflightActionExecutionId"`
}

// StatusPreflightRequestBody defines model for StatusPreflightRequestBody.
type StatusPreflightRequestBody struct {
	PreflightActionExecutionId uuid.UUID `json:"preflightActionExecutionId"`
}

// AsExperimentExecutionStepActionAO returns the union data inside the AbstractExperimentExecutionStepAO as a ExperimentExecutionStepActionAO
func (t AbstractExperimentExecutionStepAO) AsExperimentExecutionStepActionAO() (ExperimentExecutionStepActionAO, error) {
	var body ExperimentExecutionStepActionAO
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExperimentExecutionStepActionAO overwrites any union data inside the AbstractExperimentExecutionStepAO as the provided ExperimentExecutionStepActionAO
func (t *AbstractExperimentExecutionStepAO) FromExperimentExecutionStepActionAO(v ExperimentExecutionStepActionAO) error {
	t.StepType = "ACTION"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExperimentExecutionStepActionAO performs a merge with any union data inside the AbstractExperimentExecutionStepAO, using the provided ExperimentExecutionStepActionAO
func (t *AbstractExperimentExecutionStepAO) MergeExperimentExecutionStepActionAO(v ExperimentExecutionStepActionAO) error {
	t.StepType = "ACTION"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExperimentExecutionStepWaitAO returns the union data inside the AbstractExperimentExecutionStepAO as a ExperimentExecutionStepWaitAO
func (t AbstractExperimentExecutionStepAO) AsExperimentExecutionStepWaitAO() (ExperimentExecutionStepWaitAO, error) {
	var body ExperimentExecutionStepWaitAO
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExperimentExecutionStepWaitAO overwrites any union data inside the AbstractExperimentExecutionStepAO as the provided ExperimentExecutionStepWaitAO
func (t *AbstractExperimentExecutionStepAO) FromExperimentExecutionStepWaitAO(v ExperimentExecutionStepWaitAO) error {
	t.StepType = "WAIT"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExperimentExecutionStepWaitAO performs a merge with any union data inside the AbstractExperimentExecutionStepAO, using the provided ExperimentExecutionStepWaitAO
func (t *AbstractExperimentExecutionStepAO) MergeExperimentExecutionStepWaitAO(v ExperimentExecutionStepWaitAO) error {
	t.StepType = "WAIT"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AbstractExperimentExecutionStepAO) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"stepType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t AbstractExperimentExecutionStepAO) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ACTION":
		return t.AsExperimentExecutionStepActionAO()
	case "WAIT":
		return t.AsExperimentExecutionStepWaitAO()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t AbstractExperimentExecutionStepAO) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.CustomLabel != nil {
		object["customLabel"], err = json.Marshal(t.CustomLabel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'customLabel': %w", err)
		}
	}

	if t.Ended != nil {
		object["ended"], err = json.Marshal(t.Ended)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ended': %w", err)
		}
	}

	if t.Id != nil {
		object["id"], err = json.Marshal(t.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if t.IgnoreFailure != nil {
		object["ignoreFailure"], err = json.Marshal(t.IgnoreFailure)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ignoreFailure': %w", err)
		}
	}

	if t.Parameters != nil {
		object["parameters"], err = json.Marshal(t.Parameters)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parameters': %w", err)
		}
	}

	if t.PredecessorId != nil {
		object["predecessorId"], err = json.Marshal(t.PredecessorId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'predecessorId': %w", err)
		}
	}

	if t.Reason != nil {
		object["reason"], err = json.Marshal(t.Reason)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reason': %w", err)
		}
	}

	if t.Started != nil {
		object["started"], err = json.Marshal(t.Started)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'started': %w", err)
		}
	}

	if t.State != nil {
		object["state"], err = json.Marshal(t.State)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'state': %w", err)
		}
	}

	object["stepType"], err = json.Marshal(t.StepType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'stepType': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *AbstractExperimentExecutionStepAO) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["customLabel"]; found {
		err = json.Unmarshal(raw, &t.CustomLabel)
		if err != nil {
			return fmt.Errorf("error reading 'customLabel': %w", err)
		}
	}

	if raw, found := object["ended"]; found {
		err = json.Unmarshal(raw, &t.Ended)
		if err != nil {
			return fmt.Errorf("error reading 'ended': %w", err)
		}
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &t.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
	}

	if raw, found := object["ignoreFailure"]; found {
		err = json.Unmarshal(raw, &t.IgnoreFailure)
		if err != nil {
			return fmt.Errorf("error reading 'ignoreFailure': %w", err)
		}
	}

	if raw, found := object["parameters"]; found {
		err = json.Unmarshal(raw, &t.Parameters)
		if err != nil {
			return fmt.Errorf("error reading 'parameters': %w", err)
		}
	}

	if raw, found := object["predecessorId"]; found {
		err = json.Unmarshal(raw, &t.PredecessorId)
		if err != nil {
			return fmt.Errorf("error reading 'predecessorId': %w", err)
		}
	}

	if raw, found := object["reason"]; found {
		err = json.Unmarshal(raw, &t.Reason)
		if err != nil {
			return fmt.Errorf("error reading 'reason': %w", err)
		}
	}

	if raw, found := object["started"]; found {
		err = json.Unmarshal(raw, &t.Started)
		if err != nil {
			return fmt.Errorf("error reading 'started': %w", err)
		}
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &t.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
	}

	if raw, found := object["stepType"]; found {
		err = json.Unmarshal(raw, &t.StepType)
		if err != nil {
			return fmt.Errorf("error reading 'stepType': %w", err)
		}
	}

	return err
}

// AsCancelResult returns the union data inside the CancelPreflightResponse as a CancelResult
func (t CancelPreflightResponse) AsCancelResult() (CancelResult, error) {
	var body CancelResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCancelResult overwrites any union data inside the CancelPreflightResponse as the provided CancelResult
func (t *CancelPreflightResponse) FromCancelResult(v CancelResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCancelResult performs a merge with any union data inside the CancelPreflightResponse, using the provided CancelResult
func (t *CancelPreflightResponse) MergeCancelResult(v CancelResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPreflightKitError returns the union data inside the CancelPreflightResponse as a PreflightKitError
func (t CancelPreflightResponse) AsPreflightKitError() (PreflightKitError, error) {
	var body PreflightKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPreflightKitError overwrites any union data inside the CancelPreflightResponse as the provided PreflightKitError
func (t *CancelPreflightResponse) FromPreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePreflightKitError performs a merge with any union data inside the CancelPreflightResponse, using the provided PreflightKitError
func (t *CancelPreflightResponse) MergePreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CancelPreflightResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CancelPreflightResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPreflightDescription returns the union data inside the DescribePreflightResponse as a PreflightDescription
func (t DescribePreflightResponse) AsPreflightDescription() (PreflightDescription, error) {
	var body PreflightDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPreflightDescription overwrites any union data inside the DescribePreflightResponse as the provided PreflightDescription
func (t *DescribePreflightResponse) FromPreflightDescription(v PreflightDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePreflightDescription performs a merge with any union data inside the DescribePreflightResponse, using the provided PreflightDescription
func (t *DescribePreflightResponse) MergePreflightDescription(v PreflightDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPreflightKitError returns the union data inside the DescribePreflightResponse as a PreflightKitError
func (t DescribePreflightResponse) AsPreflightKitError() (PreflightKitError, error) {
	var body PreflightKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPreflightKitError overwrites any union data inside the DescribePreflightResponse as the provided PreflightKitError
func (t *DescribePreflightResponse) FromPreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePreflightKitError performs a merge with any union data inside the DescribePreflightResponse, using the provided PreflightKitError
func (t *DescribePreflightResponse) MergePreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DescribePreflightResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DescribePreflightResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPreflightList returns the union data inside the PreflightListResponse as a PreflightList
func (t PreflightListResponse) AsPreflightList() (PreflightList, error) {
	var body PreflightList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPreflightList overwrites any union data inside the PreflightListResponse as the provided PreflightList
func (t *PreflightListResponse) FromPreflightList(v PreflightList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePreflightList performs a merge with any union data inside the PreflightListResponse, using the provided PreflightList
func (t *PreflightListResponse) MergePreflightList(v PreflightList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPreflightKitError returns the union data inside the PreflightListResponse as a PreflightKitError
func (t PreflightListResponse) AsPreflightKitError() (PreflightKitError, error) {
	var body PreflightKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPreflightKitError overwrites any union data inside the PreflightListResponse as the provided PreflightKitError
func (t *PreflightListResponse) FromPreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePreflightKitError performs a merge with any union data inside the PreflightListResponse, using the provided PreflightKitError
func (t *PreflightListResponse) MergePreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PreflightListResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PreflightListResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStatusResult returns the union data inside the PreflightStatusResponse as a StatusResult
func (t PreflightStatusResponse) AsStatusResult() (StatusResult, error) {
	var body StatusResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatusResult overwrites any union data inside the PreflightStatusResponse as the provided StatusResult
func (t *PreflightStatusResponse) FromStatusResult(v StatusResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatusResult performs a merge with any union data inside the PreflightStatusResponse, using the provided StatusResult
func (t *PreflightStatusResponse) MergeStatusResult(v StatusResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPreflightKitError returns the union data inside the PreflightStatusResponse as a PreflightKitError
func (t PreflightStatusResponse) AsPreflightKitError() (PreflightKitError, error) {
	var body PreflightKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPreflightKitError overwrites any union data inside the PreflightStatusResponse as the provided PreflightKitError
func (t *PreflightStatusResponse) FromPreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePreflightKitError performs a merge with any union data inside the PreflightStatusResponse, using the provided PreflightKitError
func (t *PreflightStatusResponse) MergePreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PreflightStatusResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PreflightStatusResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStartResult returns the union data inside the StartPreflightResponse as a StartResult
func (t StartPreflightResponse) AsStartResult() (StartResult, error) {
	var body StartResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartResult overwrites any union data inside the StartPreflightResponse as the provided StartResult
func (t *StartPreflightResponse) FromStartResult(v StartResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartResult performs a merge with any union data inside the StartPreflightResponse, using the provided StartResult
func (t *StartPreflightResponse) MergeStartResult(v StartResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPreflightKitError returns the union data inside the StartPreflightResponse as a PreflightKitError
func (t StartPreflightResponse) AsPreflightKitError() (PreflightKitError, error) {
	var body PreflightKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPreflightKitError overwrites any union data inside the StartPreflightResponse as the provided PreflightKitError
func (t *StartPreflightResponse) FromPreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePreflightKitError performs a merge with any union data inside the StartPreflightResponse, using the provided PreflightKitError
func (t *StartPreflightResponse) MergePreflightKitError(v PreflightKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StartPreflightResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StartPreflightResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8DVMbOZZ/Rdc3VUnmbGMbCOCqqTsGPBtuEmDBTHY34RK5+9nW0i31SmrAl+G/bz1J",
	"/S2DyYTZmi2magJ0q6Wn9/0lfQlCkaSCA9cqGH0JJPwjA6V/FBED8+CA8hDiUwmzmM0X+qx4v8S3oeAa",
	"uMZfaZrGLKSaCb7xdyU4PlPhAhKKv6VSpCC1mzTNp9sPcfz4FsIMfzmK8O1MyITqYBQoLRmfB51AL1Oo",
	"/n3bnYuue5hlLOpdXBwdVp93WZIKaeBKqV4Eo2DO9CKb9kKRbMyFmMewgR8Gd3d3HbNpJiEKRh/uA+2y",
	"AERM/w6hth9HoELJUhwTjILJAsibyeSUOESSlC5jQSOSUqUgIloQvQCitEg3QoNaUqxIgEepYFyrHu6Z",
	"6RjXOtciJQX+iSNAcNcJzjWV+htTBm5TkCwBroud4+PvJMyCUfCfGyW3bNgp1Ma4/cn+CcL3x6Ryx4uD",
	"b0p7KvXDVMdBq8iuM/Uskd9WIkt6KINfP1lKglgqlHQxQKtUcLVCb9p3jyIR5cuTWTD6cL/82ZXOQGUx",
	"8sf9gwuAfmZ6LKWQwd2lB2k5uGQmZKGwPDx7n55yG77rBIdm7in8Htgo1jisbOipsBK5jd2PmXz7K7BT",
	"PH3L1O+CGVznyVBSYiJmyouOEgsIiB8VVrqeEBnFAk8rNH5Nf79CKdHRNPBPiQ2p//XIaBu9HBd3Hbcn",
	"o1v3p0pLGmqP53GuId0/wUF1cPaJ0pASvaCaMEXAjIeIUEVSXFTMCOWktPyo9COGMySMUy0kTpnQNEVz",
	"hyAcTI5Ojh/hEhnAQuccdYL3+0eTR379njKdO1bGdC+PaWKNMKQTNIN36LvQJEVkfvgSsCgYBVv9aX+2",
	"s7fT3RsMo+7WcPt1d3d3d6c72N7e3H492Hs9pHtBJ2BzLiT8RFmcSQhGMxor6AQplTQBDdKgPcokdegc",
	"9JXz8CIIQSkh0VHgWRzfXXYCwWENpnsISQ8x4gNouuw0XJwwU1okb+kU4jZ/HJiXJMa3hCrF5hwiEmXo",
	"3lTYAjU+m3N0GuA2laCU4W1mpJEJjnykF0wZbgsq5AgOBNeUcZDkxe3y/1+QkHLChSZTIBJouICo5VUh",
	"OXkEURvaCUtAaZqk5GYB3K5YAdKwuv20CsKwP9zs9gfd/mDS3xv1+6N+/29Bp3TuIqqhq1kCPkiYB4wL",
	"zv6RAWERbn7GQNa274QMh1ahWJMhC6iMU+gDqM6xTdjeL0AvwKqeKmoWIosjMqMs3gDUXoQlCUSMaoiX",
	"hHESUgWVPeBAZUcaR7DYh5MQB9ZUiBgoNzJRkxkaRQwhovFphRm1zKCpMJF3uyqFkM1YSMpZLE6hRd9Q",
	"8Bmb5yJZgcwnqA0vuSW5a1IWGoS1+jSVEEIEqkRbh6AqIGxGmFG3+OWMSeVAR2VLYsrhSRhDAnVmsGmR",
	"8Hmdxi2hKXaGhIeICEkM8RuidIBcxF9olN3IRAyAuwpzIe/1ej7QjA38WoG+oYrkE3wzsTag+9ShlHZh",
	"t7NSIhhvsuNL6M175Ozi+Pjo+E8d8tP+0dvxYYeMz85OzvCXg5N3p2/Hk/Hhqxrc7gM/VM6itRG1TGGF",
	"lnFwWMvcIWhh6ws6m91arxFvFotfeuRmX2vJppkGr5PBCc3fK/LyCpbdaxpn0E0pk68K54MqJULUOCb4",
	"pERTOQddF+ErWAajoOQnEzt3AjNdMAq2B4Pt4Wi4ufO64g84O2c+/eKJgq9gmYtxAWaHJHSJRqgCVJLF",
	"mqUxEGQaVaQtaAIeUCswAp8z7uUyB7YPKPOqBVZthUiEVyAfpBvuO1/KR7ofY6r0GY1YpnzEM6+JNO9L",
	"UqFzbekUwYxxsKgA4zBaZCA9yQ3E6DagDylSq++JpDwSCVHZVDWpm4IMgWs6h2C03bfaGH148xJpaT3O",
	"YP/4MKi8VcanarLGQii9wamR78q34z9f7L89zzGCnzpEdiNQV1qkGwnj7CqbQnB5d4k2wmzHil0QiqSn",
	"NNBoOWW6B7cauGKCfyqXLX5rc2BCb1mSJW0cHzndS8mM3UJEeJZMrW1B3WYQhX84K4h4dyh2ZnsKBGYz",
	"CBsqcFjRdozrzWHJK+iZzR2MFaSvBqwcVQHIEP2RQG3114OqSvr73N2JWfW0GN6gWEu2zDuCC5ZRjwOT",
	"TJf2GQ1b7llJVp+8tYSqlnxqZ5NNfDh6dEB5VyaNGJ+PXaR4BjOQwEPPbk2CL48oyc2ChQtDtPOchUka",
	"U43k2KBztFmhIV0okiTjBp/khulFL2ixMuiFiB7awhnQ6I3W6Ts72niBeuExEFMl4kwDwdc5Y9VgNxBQ",
	"rUHi+P/b6H3/3YOKz6zVyUG9LONpM3OOPVKi764T+JP2vrCZ8XlcM/cN7w/dEi3ZfA4SIjKTIiG0/VWv",
	"rgBDCdQ4Qh7vZdDrm//QiXHjfjQWjdtw9x3lGcSIJxbqTMKFjINRsNA6VaONjV6vt+Fe9FKTms4USPcp",
	"nQ8W0x2adqPh3l53a4dOu3t7u7NuOKTbm9Otzc3dYR+x45b9hVH0hY+CIhBrgDtAZ6sCbrnfX0Aqi8Lt",
	"oBMslqnQC1BM2ciElygq5M2irtC53QgSsTGjasEE705BaQVxjMMwIrEaaSFSYtwgFsfkRsgrDFap9RxR",
	"zhHpGLdt7/Z3+h1nOM7fnJx2B0EnR+c5zuJUmcrkNbuGErpURERkRmeWjnVwsIDwygCCWA46edVwBUGr",
	"GHL+ZmCdxLbpsDWxnOL3ydyFAnmeJQmVS5sVKXjqQee6xs7Iv/mn97vVg/Xd6hrffs0uDOv5/CXz3gif",
	"lTkrhCHNTC2jETdURFWgnaqEDxzt84dg/xS5++At/msY/fzgzfjw4u0Y9UiJDPPqq7MTdfXxbfMSxRZP",
	"a3y0ftw9MUnrfIwn2vamMb4E47/sY1jz6eDifHLy7tPp2cnp+GzyVyMeWXhFjoWU6EHGsbhxDmU5k8+U",
	"lks+2VaoNk8Ql1Xa5EyyQhTu2+sEOS7PR9oQFbQnRrR5swf2XSjNJkeNWwm4azvUmfqQcmTvzNXzXNpi",
	"ScIF5XNQZAr6BqCa3yUy46q6ye21vLWqIvdJZ/m+cLquacwiWnhdVazUpOB8qTQkJuiYYuwlKto4php4",
	"uMzxykGjtkcCD7b7/UQ9MmHn1RAsciDnOZ88n5OnpB4SicH2cHMtJHoD1DZoGK62Iao5FeRAJFPGaZ56",
	"/ayBJvjhZ0J5RBhHbkZT5iKNejrg8F136MOcNYxNAI8x/m2LlBYEl4iXJdfdR2RjbC1dFck4vaYsplMW",
	"M21i84VAw09jI1NRFmr1mzJcK0h9f27LJuDtK//qhbF/vKUtP/6WKSz5ldCsl04bPkU6zZNBOzgb70/G",
	"h51vnkpboazMKxcISihrYoyb9HMcQ4w8opBkPIS2Vq859R++fFUR6a7zJbBh6FG0Vt5BaQlKfQrTLOi4",
	"L39mHL/dn0z2D35es5gVptlbQaNgNOj3O1WoNvsoc6hfzch+O1m+bqba5pL+LfM99tsidLSAlrlPL9z3",
	"pTDbo4tkYj7eZQF9Y6sYqQ9v733V9ys/NZVEFyvZN6ONjcFs5/Ve1B9M98LtMBruTaeb/WFIt/qD7Z3h",
	"ztZsc3dnb3fQ3xr2dweDnenm5qC/O9ye0tc7r3d3N4GWklpBK0buQtPYpm4ORMZ1MBrgY6YhUQ+FEg9X",
	"xUvvi0pJlzYzKxn6G/d4mo+uwv7i5rQr1vVO/k4ZA60XwCQRks0Zd5poQa+BTNFZM96c7R4oKvYtLxzD",
	"/jzDYYTJzIXicPzL0dnJ8bvx8aRCWhw+2tiI4LqH0XMvt7I9dE8kp7Evy+VzWh8qXntrA+Zl9/GNCJX9",
	"PqvKZ1X5rCpXqcpmNqmUlrUL3PaTtnwyvqKx45Fi2HLQqnLZhBKfNgCzriLVmoZXHRIuAH/EgkYalH5V",
	"zezkIn7wZmx+vj3ZP/w0GZ+jPjyZvBmfBZ3gx/3zo4N6qqf4rp3Uem6geW6geW6g+fdvoCmM8X2OX72c",
	"/tx389x30+i7ye2Q7bq5XKcTx+ctNSExTeOV7otK/sJWvVyto17sZsoZ0B4xKWvTnJ7QPEVccmfe0yEB",
	"2czl52LIU+eFfjE5dDHz6+hnD+9beHhrRb3WA/QHt20XsRWVJfjcz06Gf9AzIWaeWsNJI9H9esuT6H5M",
	"W9n9vcyesvwNZZr8pkjyX9Md/tyU/exTPvuUz03Zz87hs3M4+mCPQdVcQ/PkN7Vo35+RbgH/h8hI141m",
	"PuWXAo/1ucd/OR2fHbk/ioYefD4+uMi98dVN2mu0fb7LNNV/iNbMHNI/VnvmSvy+Z3pxQOP4CLnjmhqn",
	"icbxGsftVpMMo4BmF159hQaakIxUk5m0leFlbsDdMU8NJb2nQHAyiP6bTOgVKJKbQZXrLKsSTffGoN9P",
	"1GdU758HffW5geyPH6P/esnVr4n6Vf2a/Lr4NXr13TpNypedp+PIR5CywoAVwT09MfnY0wv893CMGtkr",
	"nN5j7S3KnEpxzdDoR6BNmyidikwTSlKhFMMwtjh/2yGomDuWkjW3xZ1gUOgmLKjqkIW4Qd8aPWvEBrNN",
	"LzzqZgpdIVSbbkjZk1hZqS25tslzXcn1MWx93000VHBk1HUJqxZkATEGTZCQjEcglUb4DRbqx9eZIpFg",
	"fO71GVjoW3efE3xRhGStfrSlyGR1CSsBGeuRY4BIucwFJRHVtJtJlvsupq+XE5bQuem3TejtW+Bz1GED",
	"21tbkxT8fORVTf6QYZ9oCBfI2jE5OmyBnxm/s97hhP6js/oloclfRUZuWBzjO5wtXpIbapukMgVECVSC",
	"uJmYXQH5LOS85yxnL1l2Z5SHy24x3Wcv5mN/qLhPFllCeRddP5OvsUFj61aC1R7gb2JHe2fIV0/R0upF",
	"Jqw4b3bEwziLQPm2HruUWOXwmS+jkYo0i/NjZw1m5yu7xXrkyBpCswr6PUmqlx3CRXW92vym7zxP3rRT",
	"fM0WhFVdn+Z4mOvzdMa4wmtnkIA5PYQCZhv9bMubPVEG1yCXJkm3FBnJUnS43Z0dM8ZN+Kd6xHTMOmVv",
	"OddGsITyZWVk0UiKer88DVfiz4HZI++BRIJIQGMBPCKZonMjJQqSa5DEokH1HvQaTBhlmb1EUV3vreaR",
	"nKULxrz03ThxWJ+r6eO1z+X4FB7wBWrzqEqps58OyM5uf4ecSjGNISGHzhyhOBpTuX96pNCgpjFD/ZDf",
	"nEOmIlpalW3SACoETiUTqmVCrIFbQw/AbRpT1yFaJm+FVWEiDE1MFULJYAZiv9LnaCx8Pu4+uTg7IjIX",
	"Z2/barH44xYtNUsEM2pOWQVl8FsH4/s8QO5axi4ovaDGJbD5cNTC+eEN1bHYtkqYUPMcFbQGlbtG+LEJ",
	"fxiOQeVQ9jJX5LG+opEl4/zZ8xwdwor40NxzwhSRoDPJy8kaFy/1yPd5mG83JMGE27RirSyb3CxYXPSx",
	"I/B1yN47WBIqr2x+VOYF/VL6n2IDlUDXEgYfONr5nDwnop5DWAshdafJ2sqeG2lwkbHLXlbS3uB9Hd59",
	"YOqG6rLbqKgcd6qvcdWRv7RjTkyUdHDmq0qpmlPust5tH7OcwSS71ykl3HfisGm3OoH1io7sxFpmsPLe",
	"shXq1+DAo3cbhwkrwcKfxhMv31Sv7/l2ZzA9oNVuTWqtZPQ5eFNppoHFkM3IFbq1jGfmlEMq0F9sSw/K",
	"aSzsgbZiZpQ6k+Q1UQcXTgEwc+wk8GV+f8P2q8Qs93Z51wmKopPPlXYHb4uyzFpVyUaX33Px8BHFw/xM",
	"YZHS9BYUW71hyI5vhNL+4x6TgmNdOl2EoIozdpbIXdeThc4e8iP+PxPyhsoIWVWXfjYuTIreMJJ7EjWy",
	"I3yRPfZZngI1IDT/7va9jWQVpvGYEGiGCI3kZsRUKK7tId48xWm32SP75jDOAzdF2Mss3MFR92WjKP5E",
	"jLx2h3Tl8o51FPqqo0BHrQrMekLvudXim5bP1y63CG5vOsj5OIZriMnNonl2qV1wcdFgnuePmCm4tIaR",
	"l59tIvA/fiAvbO3hhRGP8qmrRLx4ZdaUrg6kyGeexfHnumT8ZOfXwt0iZ+6aLIu3L9fpwRTpq9WYcgFK",
	"G2En+W0eZc0whzXPsd2PzAcR2i5hmRJ0vYbl+KvYz4jALSuuKh2QlyiAP3x0Zae97nBvMhiOtgajzeHf",
	"PgbEgPSDtZWJmv/wsZQqEglQZkW4ZUp/DLxBiMhkuEJJ2nfkJetBz+R6c61XkOFV44yyK1jq3HoLe6i9",
	"jonTk/MJccWRwaA37Pd2X/eG29ujvf7e5sYjerA/mbuWUwkplY+ptp3Xq2x59GZrpT6SNyjZNkYPeeJl",
	"Ge2rFMojb+5o3ifSAufPGcg8CeKCKrQPSGGVpSAbt+BMwXRleCB7qsZ8z6bqx+m9/Jqp4tC84NxhdQFk",
	"kU3rThgkJsMQUPo/U3NNcXlnwu9wBUXDiU9ctuMrDqvi4jVG+V/KgRwKrzBUN+RZrdxIqznBvamu2iF5",
	"EbPRtFBUWmpwDTbp9XBnc6c73Rzsdrf6W7tdurMXdbd2dvei11vb03BzUE9+D7e3HwpGC4j9d0WHgqss",
	"sazWukkV/Qo+E7jZmIXg7l4tt4KcYKrVOVscTSphfFDWk6rxBbFXLhRZz2DQ6/cMyUUKnKYsGAWbvUGv",
	"b6tfC2U7pwxHRFm4CtS7fwYAAP//eHibfcpfAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
